[package]
name = "https_client"
version = "0.0.3"
authors = ["Brian Taylor <brian@resolvingarchitecture.io>"]
license-file = "LICENSE"
edition = "2018"
description = "A client for accessing web sites/services via HTTPS."
homepage = "https://resolvingarchitecture.io"
documentation = "https://github.com/resolvingarchitecture/https-client"
repository = "https://github.com/resolvingarchitecture/https-client"
publish = true
readme = "README.md"
keywords = ["https","https-client"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
simple_logger = "1.6.0"
failure = "0.1.5"
exitfailure = "0.5.1"

ra_common = "0.0.40"

[dev-dependencies]
assert_cmd = "0.10"
